# Generated by Django 3.0.3 on 2020-09-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_source',
            field=models.ImageField(height_field=250, upload_to='media/', width_field=250),
        ),
    ]
