# Generated by Django 3.0.3 on 2020-09-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20200905_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_source',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
